### ISSUE TITLE
从官网安装ros后无法rosdep init的解决方案

### ISSUE THREAD

**Issue by espla320** [haohaoalt/rikirobot#1]
从官网安装ros成功后如果无法rosdep init，可以使用小鱼配置
输入
`wget http://fishros.com/install -O fishros && . fishros`
选择3.一键配置rosdep
成功后再输入`rosdepc update`

**Comment by haohaoalt** [comment]
👍

**Comment by haohaoalt** [comment]
> 从官网安装ros成功后如果无法rosdep init，可以使用小鱼配置 输入 `wget http://fishros.com/install -O fishros && . fishros` 选择3.一键配置rosdep 成功后再输入`rosdepc update`

👍
